jobs:
  - name: dv-man-qhs5-test
    type: manifest
    steps:
      - IN: dv-image-qhs-test
        pull: false
      - IN: dv-opts-qhs-test
      - IN: dv-params-qhs-test
        applyTo:
          - dv-image-qhs-test
      - TASK: managed
     # - IN: trigger-dv-man-qhs
    on_success:
      - echo 'this is on_success step of dv-man of type manifest'
      - NOTIFY: slackNotification-qhs
    on_failure:
      - echo 'this is on_failure step of dv-man of type manifest'
      - NOTIFY: slackNotification-qhs
      
      

  - name: dv-man-versionName-qhs5-test
    type: manifest
    steps:
      - IN: dv-image-qhs-test
        pull: false
        versionName: latest
      - IN: dv-opts-qhs-test
      - IN: dv-params-qhs-test
        applyTo:
          - dv-image-qhs-test
      - TASK: managed
      - IN: trigger-dv-man-qhs-test

  - name: dv-man-versionNumber-qhs5-test
    type: manifest
    steps:
      - IN: dv-image-qhs-test
        pull: false
        versionNumber: 1
      - IN: dv-opts-qhs-test
      - IN: dv-params-qhs-test
        applyTo:
          - dv-image-qhs-test
      - TASK: managed
      - IN: trigger-dv-man-qhs-test

  - name: dv-test-qhs-test
    type: deploy
    on_start:
      - NOTIFY: slackNotification-qhs-test
    steps:
      - IN: dv-man-qhs5-test
      - IN: env-test-qhs-test
      - TASK: managed
        deployMethod: upgrade
   
    on_success:
      - NOTIFY: slackNotification-qhs-test
    on_failure:
      - NOTIFY: slackNotification-qhs-test
   

  - name: box-man-qhs5-test
    type: manifest
    steps:
      - IN: box-image-qhs-test
        pull: false
      - IN: box-opts-qhs-test
      - IN: box-params-qhs-test
      - TASK: managed

  - name: box-test-qhs5-test
    type: deploy
    steps:
      - IN: box-man-qhs-test
      - IN: env-test-qhs-test
      - TASK: managed
        deployMethod: upgrade

  
