jobs:
  - name: dv-man-qhs1
    type: manifest
    steps:
      - IN: dv-image-qhs
        pull: false
      - IN: dv-opts-qhs
      - IN: dv-params-qhs
        applyTo:
          - dv-image-qhs
      - TASK: managed
      - IN: trigger-dv-man-qhs
    on_success:
      - echo 'this is on_success step of dv-man of type manifest'
      - NOTIFY: slackNotification-qhs
    on_failure:
      - echo 'this is on_failure step of dv-man of type manifest'
      - NOTIFY: slackNotification-qhs
      
      

  - name: dv-man-versionName-qhs1
    type: manifest
    steps:
      - IN: dv-image-qhs
        pull: false
        versionName: latest
      - IN: dv-opts-qhs
      - IN: dv-params-qhs
        applyTo:
          - dv-image-qhs
      - TASK: managed
      - IN: trigger-dv-man-qhs

  - name: dv-man-versionNumber-qhs1
    type: manifest
    steps:
      - IN: dv-image-qhs
        pull: false
        versionNumber: 1
      - IN: dv-opts-qhs
      - IN: dv-params-qhs
        applyTo:
          - dv-image-qhs
      - TASK: managed
      - IN: trigger-dv-man-qhs

  - name: dv-test-qhs
    type: deploy
    on_start:
      - NOTIFY: slackNotification-qhs
    steps:
      - IN: dv-man-qhs1
      - IN: env-test-qhs
      - TASK: managed
        deployMethod: upgrade
   
    on_success:
      - NOTIFY: slackNotification-qhs
    on_failure:
      - NOTIFY: slackNotification-qhs
   

  - name: box-man-qhs
    type: manifest
    steps:
      - IN: box-image-qhs
        pull: false
      - IN: box-opts-qhs
      - IN: box-params-qhs
      - TASK: managed

  - name: box-test-qhs
    type: deploy
    steps:
      - IN: box-man-qhs
      - IN: env-test-qhs
      - TASK: managed
        deployMethod: upgrade

  
